### ISSUE TITLE
NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by Bl1nnnk** [skelsec/minidump#40]
```
~/dumps$ python3 -m minidump --all ./7.12.7_Windows_POC_Stack.dmp

# minidump 0.0.23
# Author: Tamas Jos @skelsec (skelsecprojects@gmail.com)

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/minidump-0.0.23-py3.7.egg/minidump/__main__.py", line 101, in <module>
    run()
  File "/usr/local/lib/python3.7/dist-packages/minidump-0.0.23-py3.7.egg/minidump/__main__.py", line 51, in run
    mf = MinidumpFile.parse(args.minidumpfile)
  File "/usr/local/lib/python3.7/dist-packages/minidump-0.0.23-py3.7.egg/minidump/minidumpfile.py", line 49, in parse
    mf._parse()
  File "/usr/local/lib/python3.7/dist-packages/minidump-0.0.23-py3.7.egg/minidump/minidumpfile.py", line 80, in _parse
    self.__parse_directories()
  File "/usr/local/lib/python3.7/dist-packages/minidump-0.0.23-py3.7.egg/minidump/minidumpfile.py", line 148, in __parse_directories
    self.exception = ExceptionList.parse(dir, self.file_handle)
  File "/usr/local/lib/python3.7/dist-packages/minidump-0.0.23-py3.7.egg/minidump/streams/ExceptionStream.py", line 194, in parse
    mes = MINIDUMP_EXCEPTION_STREAM.parse(chunk)
  File "/usr/local/lib/python3.7/dist-packages/minidump-0.0.23-py3.7.egg/minidump/streams/ExceptionStream.py", line 25, in parse
    mes.ExceptionRecord = MINIDUMP_EXCEPTION.parse(buff)
  File "/usr/local/lib/python3.7/dist-packages/minidump-0.0.23-py3.7.egg/minidump/streams/ExceptionStream.py", line 139, in parse
    for _ in range(self.EXCEPTION_MAXIMUM_PARAMETERS):
NameError: name 'self' is not defined
```

**Comment by skelsec** [comment]
I pushed a fix for this on the main branch
